sudo: required
services:
- docker
language: bash
script:
- docker build -t darkxahtep/climatemeter-web:latest .
deploy:
  provider: script
  script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push darkxahtep/climatemeter-web
  skip_cleanup: true
